### ISSUE TITLE
Interfaz de crear préstamos

### ISSUE THREAD

**Issue by yesserm** [jamescito/SIRAP_CLIENTE#4]
**¿Su solicitud de característica (feature) está relacionada con un problema? Por favor describa**
La manipulación de los préstamos es la tarea esencial dentro del sistema, ya que de eso se va a tratar. Entonces, es necesario obtener esos datos a través de la API, cumpliendo todas las operaciones de recursos de API necesarias.

**Describe la solución que deseas**
Esta interfaz debe ser rápida, ya que es la más utilizada, y ha de contener únicamente la crear préstamos expuesta de forma rápida, entonces las demás operaciones de mostrar préstamos, editar y eliminar han de realizarse en otra interfaz aparte, se debe cumplir con: 
- [x] Crear Préstamos

**Describe alternativas que hayas considerado**
Esta interfaz es la principal, así que debe ser rápida y concisa 

**Contexto adicional**  
Busque la manera posible que la interfaz sea liviana

**Comment by jamescito** [comment]
resuelto con #7
